enum CountriesList {
    static let all = [
        Country(name: "Afghanistan", flag: "🇦🇫", code: "AF"),
        Country(name: "Albania", flag: "🇦🇱", code: "AL"),
        Country(name: "Algeria", flag: "🇩🇿", code: "DZ"),
        Country(name: "Andorra", flag: "🇦🇩", code: "AD"),
        Country(name: "Angola", flag: "🇦🇴", code: "AO"),
        Country(name: "Antigua and Barbuda", flag: "🇦🇬", code: "AG"),
        Country(name: "Argentina", flag: "🇦🇷", code: "AR"),
        Country(name: "Armenia", flag: "🇦🇲", code: "AM"),
        Country(name: "Australia", flag: "🇦🇺", code: "AU"),
        Country(name: "Austria", flag: "🇦🇹", code: "AT"),
        Country(name: "Azerbaijan", flag: "🇦🇿", code: "AZ"),
        Country(name: "Bahamas", flag: "🇧🇸", code: "BS"),
        Country(name: "Bahrain", flag: "🇧🇭", code: "BH"),
        Country(name: "Bangladesh", flag: "🇧🇩", code: "BD"),
        Country(name: "Barbados", flag: "🇧🇧", code: "BB"),
        Country(name: "Belarus", flag: "🇧🇾", code: "BY"),
        Country(name: "Belgium", flag: "🇧🇪", code: "BE"),
        Country(name: "Belize", flag: "🇧🇿", code: "BZ"),
        Country(name: "Benin", flag: "🇧🇯", code: "BJ"),
        Country(name: "Bhutan", flag: "🇧🇹", code: "BT"),
        Country(name: "Bolivia", flag: "🇧🇴", code: "BO"),
        Country(name: "Bosnia and Herzegovina", flag: "🇧🇦", code: "BA"),
        Country(name: "Botswana", flag: "🇧🇼", code: "BW"),
        Country(name: "Brazil", flag: "🇧🇷", code: "BR"),
        Country(name: "Brunei", flag: "🇧🇳", code: "BN"),
        Country(name: "Bulgaria", flag: "🇧🇬", code: "BG"),
        Country(name: "Burkina Faso", flag: "🇧🇫", code: "BF"),
        Country(name: "Burundi", flag: "🇧🇮", code: "BI"),
        Country(name: "Cambodia", flag: "🇰🇭", code: "KH"),
        Country(name: "Cameroon", flag: "🇨🇲", code: "CM"),
        Country(name: "Canada", flag: "🇨🇦", code: "CA"),
        Country(name: "Cape Verde", flag: "🇨🇻", code: "CV"),
        Country(name: "Central African Republic", flag: "🇨🇫", code: "CF"),
        Country(name: "Chad", flag: "🇹🇩", code: "TD"),
        Country(name: "Chile", flag: "🇨🇱", code: "CL"),
        Country(name: "China", flag: "🇨🇳", code: "CN"),
        Country(name: "Colombia", flag: "🇨🇴", code: "CO"),
        Country(name: "Comoros", flag: "🇰🇲", code: "KM"),
        Country(name: "Congo", flag: "🇨🇬", code: "CG"),
        Country(name: "Costa Rica", flag: "🇨🇷", code: "CR"),
        Country(name: "Croatia", flag: "🇭🇷", code: "HR"),
        Country(name: "Cuba", flag: "🇨🇺", code: "CU"),
        Country(name: "Cyprus", flag: "🇨🇾", code: "CY"),
        Country(name: "Czech Republic", flag: "🇨🇿", code: "CZ"),
        Country(name: "Denmark", flag: "🇩🇰", code: "DK"),
        Country(name: "Djibouti", flag: "🇩🇯", code: "DJ"),
        Country(name: "Dominica", flag: "🇩🇲", code: "DM"),
        Country(name: "Dominican Republic", flag: "🇩🇴", code: "DO"),
        Country(name: "East Timor", flag: "🇹🇱", code: "TL"),
        Country(name: "Ecuador", flag: "🇪🇨", code: "EC"),
        Country(name: "Egypt", flag: "🇪🇬", code: "EG"),
        Country(name: "El Salvador", flag: "🇸🇻", code: "SV"),
        Country(name: "Equatorial Guinea", flag: "🇬🇶", code: "GQ"),
        Country(name: "Eritrea", flag: "🇪🇷", code: "ER"),
        Country(name: "Estonia", flag: "🇪🇪", code: "EE"),
        Country(name: "Ethiopia", flag: "🇪🇹", code: "ET"),
        Country(name: "Fiji", flag: "🇫🇯", code: "FJ"),
        Country(name: "Finland", flag: "🇫🇮", code: "FI"),
        Country(name: "France", flag: "🇫🇷", code: "FR"),
        Country(name: "Gabon", flag: "🇬🇦", code: "GA"),
        Country(name: "Gambia", flag: "🇬🇲", code: "GM"),
        Country(name: "Georgia", flag: "🇬🇪", code: "GE"),
        Country(name: "Germany", flag: "🇩🇪", code: "DE"),
        Country(name: "Ghana", flag: "🇬🇭", code: "GH"),
        Country(name: "Greece", flag: "🇬🇷", code: "GR"),
        Country(name: "Grenada", flag: "🇬🇩", code: "GD"),
        Country(name: "Guatemala", flag: "🇬🇹", code: "GT"),
        Country(name: "Guinea", flag: "🇬🇳", code: "GN"),
        Country(name: "Guinea-Bissau", flag: "🇬🇼", code: "GW"),
        Country(name: "Guyana", flag: "🇬🇾", code: "GY"),
        Country(name: "Haiti", flag: "🇭🇹", code: "HT"),
        Country(name: "Honduras", flag: "🇭🇳", code: "HN"),
        Country(name: "Hungary", flag: "🇭🇺", code: "HU"),
        Country(name: "Iceland", flag: "🇮🇸", code: "IS"),
        Country(name: "India", flag: "🇮🇳", code: "IN"),
        Country(name: "Indonesia", flag: "🇮🇩", code: "ID"),
        Country(name: "Iran", flag: "🇮🇷", code: "IR"),
        Country(name: "Iraq", flag: "🇮🇶", code: "IQ"),
        Country(name: "Ireland", flag: "🇮🇪", code: "IE"),
        Country(name: "Israel", flag: "🇮🇱", code: "IL"),
        Country(name: "Italy", flag: "🇮🇹", code: "IT"),
        Country(name: "Jamaica", flag: "🇯🇲", code: "JM"),
        Country(name: "Japan", flag: "🇯🇵", code: "JP"),
        Country(name: "Jordan", flag: "🇯🇴", code: "JO"),
        Country(name: "Kazakhstan", flag: "🇰🇿", code: "KZ"),
        Country(name: "Kenya", flag: "🇰🇪", code: "KE"),
        Country(name: "Kiribati", flag: "🇰🇮", code: "KI"),
        Country(name: "North Korea", flag: "🇰🇵", code: "KP"),
        Country(name: "South Korea", flag: "🇰🇷", code: "KR"),
        Country(name: "Kuwait", flag: "🇰🇼", code: "KW"),
        Country(name: "Kyrgyzstan", flag: "🇰🇬", code: "KG"),
        Country(name: "Laos", flag: "🇱🇦", code: "LA"),
        Country(name: "Latvia", flag: "🇱🇻", code: "LV"),
        Country(name: "Lebanon", flag: "🇱🇧", code: "LB"),
        Country(name: "Lesotho", flag: "🇱🇸", code: "LS"),
        Country(name: "Liberia", flag: "🇱🇷", code: "LR"),
        Country(name: "Libya", flag: "🇱🇾", code: "LY"),
        Country(name: "Liechtenstein", flag: "🇱🇮", code: "LI"),
        Country(name: "Lithuania", flag: "🇱🇹", code: "LT"),
        Country(name: "Luxembourg", flag: "🇱🇺", code: "LU"),
        Country(name: "Madagascar", flag: "🇲🇬", code: "MG"),
        Country(name: "Malawi", flag: "🇲🇼", code: "MW"),
        Country(name: "Malaysia", flag: "🇲🇾", code: "MY"),
        Country(name: "Maldives", flag: "🇲🇻", code: "MV"),
        Country(name: "Mali", flag: "🇲🇱", code: "ML"),
        Country(name: "Malta", flag: "🇲🇹", code: "MT"),
        Country(name: "Marshall Islands", flag: "🇲🇭", code: "MH"),
        Country(name: "Mauritania", flag: "🇲🇷", code: "MR"),
        Country(name: "Mauritius", flag: "🇲🇺", code: "MU"),
        Country(name: "Mexico", flag: "🇲🇽", code: "MX"),
        Country(name: "Micronesia", flag: "🇫🇲", code: "FM"),
        Country(name: "Moldova", flag: "🇲🇩", code: "MD"),
        Country(name: "Monaco", flag: "🇲🇨", code: "MC"),
        Country(name: "Mongolia", flag: "🇲🇳", code: "MN"),
        Country(name: "Montenegro", flag: "🇲🇪", code: "ME"),
        Country(name: "Morocco", flag: "🇲🇦", code: "MA"),
        Country(name: "Mozambique", flag: "🇲🇿", code: "MZ"),
        Country(name: "Myanmar", flag: "🇲🇲", code: "MM"),
        Country(name: "Namibia", flag: "🇳🇦", code: "NA"),
        Country(name: "Nauru", flag: "🇳🇷", code: "NR"),
        Country(name: "Nepal", flag: "🇳🇵", code: "NP"),
        Country(name: "Netherlands", flag: "🇳🇱", code: "NL"),
        Country(name: "New Zealand", flag: "🇳🇿", code: "NZ"),
        Country(name: "Nicaragua", flag: "🇳🇮", code: "NI"),
        Country(name: "Niger", flag: "🇳🇪", code: "NE"),
        Country(name: "Nigeria", flag: "🇳🇬", code: "NG"),
        Country(name: "Norway", flag: "🇳🇴", code: "NO"),
        Country(name: "Oman", flag: "🇴🇲", code: "OM"),
        Country(name: "Pakistan", flag: "🇵🇰", code: "PK"),
        Country(name: "Palau", flag: "🇵🇼", code: "PW"),
        Country(name: "Palestine", flag: "🇵🇸", code: "PS"),
        Country(name: "Panama", flag: "🇵🇦", code: "PA"),
        Country(name: "Papua New Guinea", flag: "🇵🇬", code: "PG"),
        Country(name: "Paraguay", flag: "🇵🇾", code: "PY"),
        Country(name: "Peru", flag: "🇵🇪", code: "PE"),
        Country(name: "Philippines", flag: "🇵🇭", code: "PH"),
        Country(name: "Poland", flag: "🇵🇱", code: "PL"),
        Country(name: "Portugal", flag: "🇵🇹", code: "PT"),
        Country(name: "Qatar", flag: "🇶🇦", code: "QA"),
        Country(name: "Romania", flag: "🇷🇴", code: "RO"),
        Country(name: "Russia", flag: "🇷🇺", code: "RU"),
        Country(name: "Rwanda", flag: "🇷🇼", code: "RW"),
        Country(name: "Saint Kitts and Nevis", flag: "🇰🇳", code: "KN"),
        Country(name: "Saint Lucia", flag: "🇱🇨", code: "LC"),
        Country(name: "Saint Martin", flag: "🇲🇫", code: "MF"),
        Country(name: "Saint Pierre and Miquelon", flag: "🇵🇲", code: "PM"),
        Country(name: "Saint Vincent and the Grenadines", flag: "🇻🇨", code: "VC"),
        Country(name: "Samoa", flag: "🇼🇸", code: "WS"),
        Country(name: "San Marino", flag: "🇸🇲", code: "SM"),
        Country(name: "Sao Tome and Principe", flag: "🇸🇹", code: "ST"),
        Country(name: "Saudi Arabia", flag: "🇸🇦", code: "SA"),
        Country(name: "Senegal", flag: "🇸🇳", code: "SN"),
        Country(name: "Serbia", flag: "🇷🇸", code: "RS"),
        Country(name: "Seychelles", flag: "🇸🇨", code: "SC"),
        Country(name: "Sierra Leone", flag: "🇸🇱", code: "SL"),
        Country(name: "Singapore", flag: "🇸🇬", code: "SG"),
        Country(name: "Sint Maarten", flag: "🇸🇽", code: "SX"),
        Country(name: "Slovakia", flag: "🇸🇰", code: "SK"),
        Country(name: "Slovenia", flag: "🇸🇮", code: "SI"),
        Country(name: "Solomon Islands", flag: "🇸🇧", code: "SB"),
        Country(name: "Somalia", flag: "🇸🇴", code: "SO"),
        Country(name: "South Africa", flag: "🇿🇦", code: "ZA"),
        Country(name: "South Korea", flag: "🇰🇷", code: "KR"),
        Country(name: "South Sudan", flag: "🇸🇸", code: "SS"),
        Country(name: "Spain", flag: "🇪🇸", code: "ES"),
        Country(name: "Sri Lanka", flag: "🇱🇰", code: "LK"),
        Country(name: "Sudan", flag: "🇸🇩", code: "SD"),
        Country(name: "Suriname", flag: "🇸🇷", code: "SR"),
        Country(name: "Sweden", flag: "🇸🇪", code: "SE"),
        Country(name: "Switzerland", flag: "🇨🇭", code: "CH"),
        Country(name: "Syria", flag: "🇸🇾", code: "SY"),
        Country(name: "Taiwan", flag: "🇹🇼", code: "TW"),
        Country(name: "Tajikistan", flag: "🇹🇯", code: "TJ"),
        Country(name: "Tanzania", flag: "🇹🇿", code: "TZ"),
        Country(name: "Thailand", flag: "🇹🇭", code: "TH"),
        Country(name: "Timor-Leste", flag: "🇹🇱", code: "TL"),
        Country(name: "Togo", flag: "🇹🇬", code: "TG"),
        Country(name: "Tonga", flag: "🇹🇴", code: "TO"),
        Country(name: "Trinidad and Tobago", flag: "🇹🇹", code: "TT"),
        Country(name: "Tunisia", flag: "🇹🇳", code: "TN"),
        Country(name: "Turkey", flag: "🇹🇷", code: "TR"),
        Country(name: "Turkmenistan", flag: "🇹🇲", code: "TM"),
        Country(name: "Turks and Caicos Islands", flag: "🇹🇨", code: "TC"),
        Country(name: "Tuvalu", flag: "🇹🇻", code: "TV"),
        Country(name: "Uganda", flag: "🇺🇬", code: "UG"),
        Country(name: "Ukraine", flag: "🇺🇦", code: "UA"),
        Country(name: "United Arab Emirates", flag: "🇦🇪", code: "AE"),
        Country(name: "United Kingdom", flag: "🇬🇧", code: "GB"),
        Country(name: "United States", flag: "🇺🇸", code: "US"),
        Country(name: "Uruguay", flag: "🇺🇾", code: "UY"),
        Country(name: "Uzbekistan", flag: "🇺🇿", code: "UZ"),
        Country(name: "Vanuatu", flag: "🇻🇺", code: "VU"),
        Country(name: "Vatican City", flag: "🇻🇦", code: "VA"),
        Country(name: "Venezuela", flag: "🇻🇪", code: "VE"),
        Country(name: "Vietnam", flag: "🇻🇳", code: "VN"),
        Country(name: "Virgin Islands (British)", flag: "🇻🇬", code: "VG"),
        Country(name: "Virgin Islands (US)", flag: "🇻🇮", code: "VI"),
        Country(name: "Yemen", flag: "🇾🇪", code: "YE"),
        Country(name: "Zambia", flag: "🇿🇲", code: "ZM"),
        Country(name: "Zimbabwe", flag: "🇿🇼", code: "ZW"),
    ]
}
